name: SocialNetwork.WebApi Build and Deploy

on: 
  push:
    branches: 
      - master
    paths:
      - 'SocialNetwork/SocialNetwork.Bll/**'
      - 'SocialNetwork/SocialNetwork.Dal/**'
      - 'SocialNetwork/SocialNetwork.Security/**'
      - 'SocialNetwork/SocialNetwork.Utilities/**'
      - 'SocialNetwork/SocialNetwork.WebApi/**'
      - 'SocialNetwork/SocialNetwork.Markdown/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      id: building
      run: dotnet build SocialNetwork/SocialNetwork.WebApi/SocialNetwork.WebApi.csproj --configuration Release
    - name: Notify when builded success
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: "-373392644"
        token: "914543704:AAGxCfEN279RPLCAFsFTsQR2ava6P13c5ZE"
        message: |
          📃 ${{ github.workflow }}
          👺 ${{ github.actor }}
          ✅ Success!
    - name: Notify when builded failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: "-373392644"
        token: "914543704:AAGxCfEN279RPLCAFsFTsQR2ava6P13c5ZE"
        message: |
          📃 ${{ github.workflow }}
          👺 ${{ github.actor }}
          ❌ Failure!
    - name: List builded files
      run: ls
    - name: Copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "SocialNetwork/SocialNetwork.WebApi/bin/Release/netcoreapp3.0/*"
        target: "SocialNetwork.WebApi.Builded"
    - name: Downloading service-check script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: wget "https://raw.githubusercontent.com/OneZeroZeroOneOne/SocialNetwork/master/service-check" -O "/root/service-check"
    - name: Giving rights for service check
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: chmod +rx "/root/service-check"
    - name: Starting service-check
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: /root/service-check social-network-webapi.service

